import json
import os
import pandas as pd
import re

from modeling import get_paraphrase_chatgpt, translate_paraphrases

def get_paraphrase_df(df: pd.DataFrame):
    """Create dataframe of english paraphrases generated by chatGPT. Creates up to two paraphrases per phrase."""
    df = df.assign(en_para_1=None, en_para_2=None)
    for i, row in df.iterrows():
        if len(row["en_source"].split(" ")) == 1:
            continue
        paraph_list = get_paraphrase_chatgpt(row["en_source"])
        for j, phrase in enumerate(paraph_list):
            df.loc[i, f"en_para_{j+1}"] = phrase
    df = df.dropna(subset=["en_para_1"])
    return df

def join_para_files(name: str) -> pd.DataFrame:
    with open(f"data/gpt_paraphrase/{name}_para_gpt.json", encoding="utf-8") as j:
        df_og = pd.DataFrame.from_dict(json.load(j), orient="index")
    with open(f"data/gpt_paraphrase/{name}_para_gpt_prompt2.json", encoding="utf-8") as j2:
        df_new = pd.DataFrame.from_dict(json.load(j2), orient="index")
    for i, row in df_og.iterrows():
        if i not in df_new.index:
            continue
        phrase_list = []
        for j in range(1,5):
            if f"en_para_{j}" in row:
                phrase_list.append(row[f"en_para_{j}"])
            else: break
        for k in range(1,5):
            if f"en_para_{k}" in row:
                new_para = df_new.loc[i, f"en_para_{k}"] 
                if new_para not in phrase_list:
                    phrase_list.append(new_para)
                    df_og.loc[i, f"en_para_{j}"] = new_para
                    j += 1
    return df_og

